Unify all versions into one script (#19)
* removed upgrade

* cleaning up script

* added CPU thread prompt

* misc cleanup

* moving config files into directory

* forgot placeholder

* wrong archive format

* added config files

* hopefully final, prepare to merge

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -2,30 +2,101 @@
 
 set -e
 
-ORIGINALPATH="$PWD"
-LOG="$ORIGINALPATH/FasterMelee/log.txt"
-COMMITHASH="dd88b80e231f79e2f257dfe793adfe5a4431ec8d"
-REPLACEFILENAME="FM_reqFiles.tar.gz"
-REPLACEFILELINK="https://github.com/Ptomerty/FasterMelee-installer/raw/master/$REPLACEFILENAME"
-GITCLONELINK="https://github.com/HannesMann/Ishiiruka"
+# Source: https://gist.github.com/jj1bdx/5746298
 
-echo "tail -f $LOG for more info!"
+# Linux and similar...
+CPUS=$(getconf _NPROCESSORS_ONLN 2>/dev/null)
+# FreeBSD and similar...
+[ -z "$CPUS" ] && CPUS=$(getconf NPROCESSORS_ONLN)
+# Solaris and similar...
+[ -z "$CPUS" ] && CPUS=$(ksh93 -c 'getconf NPROCESSORS_ONLN')
+# Give up...
+[ -z "$CPUS" ] && CPUS=1
 
-mkdir -p FasterMelee && cd FasterMelee
+echo "tail -f $LOG to follow along with the log, or for troubleshooting!"
+
+#all of the 2> /dev/nulls redirect useless errors (e.g. entering a newline) to devnull
+
+echo "" # easiest way to print newline while preserving compatibility :P
+echo "Would you like to overwrite all of your previous installations? (y/N)"
+read -r RESP
+
+if [ "$RESP" = "y" ] 2> /dev/null || [ "$RESP" = "Y" ] 2> /dev/null; then
+	echo "Are you sure? This action is not reversible! (y/N)"
+	read -r RESP
+	if [ "$RESP" = "y" ] 2> /dev/null || [ "$RESP" = "Y" ] 2> /dev/null; then
+		rm -rf FasterMelee*/ 2> /dev/null
+		echo "Deleted all FM folders!"
+	fi
+fi
+
+echo ""
+echo "Which version of Faster Melee would you like to install? (default: 1)"
+echo "1.) 5.5 (Discord default)"
+echo "2.) 5.0.3 (SmashLadder default)"
+read -r RESP
+
+if [ "$RESP" -ge 1 ] 2> /dev/null && [ "$RESP" -le 2 ] 2> /dev/null; then
+	 if [ "$RESP" -eq 1 ]; then
+	 	FMVERSION="5.5"
+		COMMITHASH="dd88b80e231f79e2f257dfe793adfe5a4431ec8d"
+		GITCLONELINK="https://github.com/HannesMann/Ishiiruka"
+	 elif [ "$RESP" -eq 2 ]; then
+	 	FMVERSION="5.0.3"
+		COMMITHASH="d462ca38724db65d7f92f3edbd16b6657291e420"
+		GITCLONELINK="https://github.com/Tinob/Ishiiruka"
+	 fi
+else
+	FMVERSION="5.5"
+	COMMITHASH="dd88b80e231f79e2f257dfe793adfe5a4431ec8d"
+	GITCLONELINK="https://github.com/HannesMann/Ishiiruka"
+fi
+
+echo "Installing version $FMVERSION!"
+
+REPLACEFILELINK="https://github.com/Ptomerty/FasterMelee-installer/raw/master/config/$FMVERSION-fmconfig.tar.gz"
+FOLDERNAME="FasterMelee-$FMVERSION-$(date +%F)"
+LOG="$(pwd)/$FOLDERNAME/log.txt"
+
+echo ""
+echo "Would you like to install rules for your Wii U adapter? (Y/n)"
+read -r RESP
+
+if [ ! "$RESP" = "n" ] && [ ! "$RESP" = "N" ]; then
+	sudo rm -f /etc/udev/rules.d/51-gcadapter.rules 2> /dev/null # remove even if doesn't exist
+	# sudo touch /etc/udev/rules.d/51-gcadapter.rules
+	echo 'SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="0337", MODE="0666"' | sudo tee /etc/udev/rules.d/51-gcadapter.rules > /dev/null # pipe to write-protected file, remove STDOUT
+	sudo udevadm control --reload-rules
+	echo "Rules added!" # set -e will take care of if/else
+fi
+
+
+echo ""
+echo "CPU Threads detected: $CPUS"
+echo "How many threads would you like to use to compile? (passed to make as -j flag, default: 1, max: $((CPUS + 1)))"
+read -r RESP
+
+if [ "$RESP" -ge 1 ] 2> /dev/null && [ "$RESP" -le $((CPUS + 1)) ] 2> /dev/null; then
+	CPUS=$RESP 
+else
+	CPUS=1
+fi
+
+echo "Using $CPUS thread(s)!"
+echo ""
+
+mkdir "$FOLDERNAME" && cd "$FOLDERNAME"
+
 echo "Downloading required replacement files..."
 wget $REPLACEFILELINK
 echo "Extracting..."
-tar -xzf $REPLACEFILENAME
-rm $REPLACEFILENAME
-
-echo "Adding adapter support (requires sudo permissions)..."
-sh adaptersetup
+tar -xzf "$FMVERSION-fmconfig.tar.gz" && rm "$FMVERSION-fmconfig.tar.gz"	
 
 echo "Cloning repo (may take a while)..."
 git clone $GITCLONELINK
 cd Ishiiruka
 echo "Switching to latest commit..."
-git checkout $COMMITHASH >>"$LOG" 2>&1
+git checkout $COMMITHASH >> "$LOG" 2>&1
 
 echo "Adding portable files..."
 mkdir build && cd build
@@ -35,15 +106,17 @@ echo "cmaking..."
 cmake .. -DLINUX_LOCAL_DEV=true >>"$LOG" 2>&1
 
 echo "Compiling...(Verbose, will take a while)"
-make 2>>"$LOG" #gets rid of errors as to not cause confusion
+make -j $CPUS 2>>"$LOG" # gets rid of errors as to not cause confusion
 
 echo "Cleaning up..."
-rm "$ORIGINALPATH/FasterMelee/log.txt"
+rm "$LOG"
 cd ../..
 mv Ishiiruka/build/Binaries/ bin/
 rm -rf Ishiiruka # -f required to remove git files
-ln -s FasterMelee/bin/dolphin-emu ../launch-faster-melee
+rm ../launch-faster-melee 2> /dev/null
+rm ../launch-fm 2> /dev/null
+ln -s "$FOLDERNAME/bin/dolphin-emu" ../launch-fm
 
-echo 'Done! Run ./launch-faster-melee to run!'
-echo 'Make sure to unplug and replug your adapter before opening Dolphin!'
+echo 'Done! Run ./launch-fm to run the latest installed version!'
+echo 'Make sure to unplug and replug your adapter before opening Dolphin for it to function!'
 
