cleaning up script

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -3,11 +3,26 @@
 set -e
 
 ORIGINALPATH="$PWD"
-LOG="$ORIGINALPATH/FasterMelee/log.txt"
 COMMITHASH="dd88b80e231f79e2f257dfe793adfe5a4431ec8d"
 REPLACEFILENAME="FM_reqFiles.tar.gz"
 REPLACEFILELINK="https://github.com/Ptomerty/FasterMelee-installer/raw/master/$REPLACEFILENAME"
 GITCLONELINK="https://github.com/HannesMann/Ishiiruka"
+FMVERSION="5.5"
+DAY=$(date +%D)
+FOLDERNAME="FasterMelee-$FMVERSION-$DAY"
+LOG="$ORIGINALPATH/$FOLDERNAME/log.txt"
+
+# Source: https://gist.github.com/jj1bdx/5746298
+# `` kept in for legacy support, could replace with $(...)
+
+# Linux and similar...
+CPUS=$(getconf _NPROCESSORS_ONLN 2>/dev/null)
+# FreeBSD and similar...
+[ -z "$CPUS" ] && CPUS=$(getconf NPROCESSORS_ONLN)
+# Solaris and similar...
+[ -z "$CPUS" ] && CPUS=$(ksh93 -c 'getconf NPROCESSORS_ONLN')
+# Give up...
+[ -z "$CPUS" ] && CPUS=1
 
 install() {
 	echo "Downloading required replacement files..."
@@ -17,7 +32,7 @@ install() {
 	rm $REPLACEFILENAME
 
 	echo "Adding adapter support (requires sudo permissions)..."
-	sh adaptersetup
+	adapter
 
 	echo "Cloning repo (may take a while)..."
 	git clone $GITCLONELINK
@@ -33,33 +48,37 @@ install() {
 	cmake .. -DLINUX_LOCAL_DEV=true >>"$LOG" 2>&1
 
 	echo "Compiling...(Verbose, will take a while)"
-	make 2>>"$LOG" #gets rid of errors as to not cause confusion
+	make -j$CPUS 2>>"$LOG" # gets rid of errors as to not cause confusion
 
 	echo "Cleaning up..."
 	rm "$ORIGINALPATH/FasterMelee/log.txt"
 	cd ../..
 	mv Ishiiruka/build/Binaries/ bin/
 	rm -rf Ishiiruka # -f required to remove git files
-	ln -s FasterMelee/bin/dolphin-emu ../launch-faster-melee
+	ln -s FasterMelee/bin/dolphin-emu ../launch-fm
 
-	echo 'Done! Run ./launch-faster-melee to run!'
-	echo 'Make sure to unplug and replug your adapter before opening Dolphin!'
+	echo 'Done! Run ./launch-fm to run!'
+	echo 'Make sure to unplug and replug your adapter before opening Dolphin for it to function!'
 }
 
+adapter() {
+	sudo rm /etc/udev/rules.d/51-gcadapter.rules 2> /dev/null # remove even if doesn't exist
+	# sudo touch /etc/udev/rules.d/51-gcadapter.rules
+	echo 'SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="0337", MODE="0666"' | sudo tee /etc/udev/rules.d/51-gcadapter.rules > /dev/null # pipe to write-protected file, remove STDOUT
+	sudo udevadm control --reload-rules
+	echo "Rules added!" # set -e will take care of if/else
+}
 
-echo "tail -f $LOG for more info!"
+echo "tail -f $LOG to follow along with the log, or for troubleshooting!"
 
-mkdir -p FasterMelee && cd FasterMelee
-
-echo "Warning! This script will erase all previous Faster Melee files in the current directory! Are you sure you want to continue? (y/n) "
+echo "Would you like to overwrite your previous installations? (y/N)"
 read -r RESP
 
 if [ ! "$RESP" = "y" ]; then
-	echo "Exiting..."
-	exit
-else
-	rm -r FasterMelee/ launch-faster-melee
+	rm -r FasterMelee*/ launch-faster-melee launch-fm
 fi
+
+mkdir $FOLDERNAME && cd $FOLDERNAME
 
 install
 
